version: '3'
services:
  akkavis1:
    build:
      context: .
    image: kinzal/akkavis
    ports:
      - "8080:8080"
    networks:
      default:
        ipv4_address: 192.168.96.2
  akkavis2:
    build:
      context: .
    image: kinzal/akkavis
    networks:
      default:
        ipv4_address: 192.168.96.3
  akkavis3:
    build:
      context: .
    image: kinzal/akkavis
    networks:
      default:
        ipv4_address: 192.168.96.4

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.96.0/20